import LUTCore
import LUTFormats

public enum Tricubic3DInverseStatus: Equatable, Sendable {
    case unique
    case multiple
    case noSolution
    case unresolved
    case nonFinite
}

public struct Tricubic3DInverseSolution: Equatable, Sendable {
    public let input: RGB64
    public let residual: Double
}

public struct Tricubic3DInverseReport: Equatable, Sendable {
    public let status: Tricubic3DInverseStatus
    public let solutions: [Tricubic3DInverseSolution]
    public let unresolvedCellCount: Int
    /// Number of tricubic cells visited in the complete `(size - 1)^3`
    /// partition. This counts enumeration only and is not a proof of roots.
    public let enumeratedCellCount: Int
    /// Number of cells whose certified Bernstein output bounds contain the
    /// target and therefore require root isolation or a conservative
    /// unresolved result.
    public let candidateCellCount: Int
    public let isGloballyComplete: Bool
}

public enum Tricubic3DInverseError: Error, Equatable, Sendable {
    case invalidTolerance
    case invalidMaxCells
    case unsupportedLUT
}

/// Conservative diagnostics for the legacy tensor-product cubic sampler.
/// Cell candidates are generated by Newton iterations, then accepted only
/// after replay through the production `LegacyTricubicVolume3D` sampler. A
/// cell whose certified output bounds contain the target but whose root cannot
/// be proved is reported as unresolved rather than being called no-solution.
public enum Tricubic3DInverse {
    public static func analyze(_ output: RGB64,
                               in volume: LUTVolume3D,
                               tolerance: Double = 2e-12,
                               maxCells: Int = 100_000) throws -> Tricubic3DInverseReport {
        try Task.checkCancellation()
        guard tolerance.isFinite, tolerance >= 0 else {
            throw Tricubic3DInverseError.invalidTolerance
        }
        guard maxCells > 0 else { throw Tricubic3DInverseError.invalidMaxCells }
        guard output.r.isFinite, output.g.isFinite, output.b.isFinite else {
            return Tricubic3DInverseReport(status: .nonFinite, solutions: [],
                                           unresolvedCellCount: 0,
                                           enumeratedCellCount: 0,
                                           candidateCellCount: 0,
                                           isGloballyComplete: false)
        }
        let n = volume.size
        guard n >= 4 else { throw Tricubic3DInverseError.unsupportedLUT }
        let cellsPerAxis = n - 1
        let (square, squareOverflow) = cellsPerAxis.multipliedReportingOverflow(by: cellsPerAxis)
        let (cellCount, cubeOverflow) = square.multipliedReportingOverflow(by: cellsPerAxis)
        guard !squareOverflow, !cubeOverflow, cellCount <= maxCells else {
            throw Tricubic3DInverseError.invalidMaxCells
        }

        let sampler: LegacyTricubicVolume3D
        do {
            sampler = try LegacyTricubicVolume3D(size: volume.size,
                                                  domain: volume.domain,
                                                  samples: volume.samples)
        } catch {
            throw Tricubic3DInverseError.unsupportedLUT
        }

        var solutions: [Tricubic3DInverseSolution] = []
        var unresolved = 0
        var candidates = 0
        for bz in 0..<cellsPerAxis {
            for by in 0..<cellsPerAxis {
                for bx in 0..<cellsPerAxis {
                    try Task.checkCancellation()
                    let cell = [bx, by, bz]
                    let bounds = try sampler.cellOutputBounds(cell)
                    guard contains(output, in: bounds, tolerance: tolerance) else { continue }
                    candidates += 1

                    let result = try solveCell(output: output, cell: cell, volume: volume,
                                               sampler: sampler, tolerance: tolerance)
                    if result.unresolved { unresolved += 1 }
                    for solution in result.solutions {
                        upsert(solution: solution, into: &solutions)
                    }
                }
            }
        }

        solutions.sort {
            if $0.input.r != $1.input.r { return $0.input.r < $1.input.r }
            if $0.input.g != $1.input.g { return $0.input.g < $1.input.g }
            return $0.input.b < $1.input.b
        }
        let status: Tricubic3DInverseStatus
        if unresolved > 0 { status = .unresolved }
        else if solutions.count > 1 { status = .multiple }
        else if solutions.count == 1 { status = .unique }
        else { status = .noSolution }
        return Tricubic3DInverseReport(status: status,
                                       solutions: solutions,
                                       unresolvedCellCount: unresolved,
                                       enumeratedCellCount: cellCount,
                                       candidateCellCount: candidates,
                                       isGloballyComplete: unresolved == 0)
    }

    public static func analyze(_ output: RGB64,
                               in lut: CubeLUT,
                               tolerance: Double = 2e-12,
                               maxCells: Int = 100_000) throws -> Tricubic3DInverseReport {
        guard lut.dimension == .three, lut.shaper == nil else {
            throw Tricubic3DInverseError.unsupportedLUT
        }
        let volume = try LUTVolume3D(size: lut.size, domain: lut.domain,
                                     samples: lut.samples)
        return try analyze(output, in: volume, tolerance: tolerance,
                           maxCells: maxCells)
    }

    private struct CellResult {
        var solutions: [Tricubic3DInverseSolution]
        var unresolved: Bool
    }

    private static let seeds: [[Double]] = {
        var values: [[Double]] = []
        for z in [0.125, 0.375, 0.625, 0.875] {
            for y in [0.125, 0.375, 0.625, 0.875] {
                for x in [0.125, 0.375, 0.625, 0.875] {
                    values.append([x, y, z])
                }
            }
        }
        return values
    }()

    private static func solveCell(output: RGB64,
                                  cell: [Int],
                                  volume: LUTVolume3D,
                                  sampler: LegacyTricubicVolume3D,
                                  tolerance: Double) throws -> CellResult {
        let cellMin = [volume.domain.min.r + Double(cell[0]) *
                           (volume.domain.max.r - volume.domain.min.r) / Double(volume.size - 1),
                       volume.domain.min.g + Double(cell[1]) *
                           (volume.domain.max.g - volume.domain.min.g) / Double(volume.size - 1),
                       volume.domain.min.b + Double(cell[2]) *
                           (volume.domain.max.b - volume.domain.min.b) / Double(volume.size - 1)]
        let cellMax = [volume.domain.min.r + Double(cell[0] + 1) *
                           (volume.domain.max.r - volume.domain.min.r) / Double(volume.size - 1),
                       volume.domain.min.g + Double(cell[1] + 1) *
                           (volume.domain.max.g - volume.domain.min.g) / Double(volume.size - 1),
                       volume.domain.min.b + Double(cell[2] + 1) *
                           (volume.domain.max.b - volume.domain.min.b) / Double(volume.size - 1)]

        var roots: [Tricubic3DInverseSolution] = []
        for seed in seeds {
            try Task.checkCancellation()
            var input = zip(cellMin, cellMax).enumerated().map {
                $0.element.0 + seed[$0.offset] * ($0.element.1 - $0.element.0)
            }
            var converged = false
            for _ in 0..<48 {
                try Task.checkCancellation()
                guard let inputRGB = try? RGB64(input[0], input[1], input[2]),
                      let evaluation = try? sampler.sampleWithJacobian(inputRGB, outside: .reject) else {
                    break
                }
                guard let difference = try? RGB64(evaluation.value.r - output.r,
                                                  evaluation.value.g - output.g,
                                                  evaluation.value.b - output.b) else {
                    break
                }
                let scale = max(1, abs(output.r), abs(output.g), abs(output.b))
                let residual = max(abs(difference.r), abs(difference.g), abs(difference.b))
                if residual <= tolerance * scale {
                    converged = true
                    break
                }
                guard let delta = try? evaluation.jacobian.solving(difference),
                      delta.r.isFinite, delta.g.isFinite, delta.b.isFinite else {
                    break
                }
                let next = [input[0] - delta.r, input[1] - delta.g, input[2] - delta.b]
                guard next.allSatisfy({ $0.isFinite }) else {
                    break
                }
                let clamped = zip(next, zip(cellMin, cellMax)).map { pair in
                    min(max(pair.0, pair.1.0), pair.1.1)
                }
                if max(abs(clamped[0] - input[0]), abs(clamped[1] - input[1]),
                       abs(clamped[2] - input[2])) <= 32 * Double.ulpOfOne *
                    max(1, abs(input[0]), abs(input[1]), abs(input[2])) {
                    break
                }
                input = clamped
            }
            guard converged else {
                // The certified output bounds only prove that a root may be
                // present.  A Newton seed that exhausts its iteration budget
                // has not proved either existence or absence, regardless of
                // whether the Jacobian was singular.  Keep that cell
                // explicitly unresolved instead of silently reporting no
                // solution.
                continue
            }

            guard let inputRGB = try? RGB64(input[0], input[1], input[2]),
                  let replay = try? sampler.sample(inputRGB, outside: .reject) else {
                continue
            }
            let residual = replayResidual(replay, target: output)
            let scale = max(1, abs(output.r), abs(output.g), abs(output.b))
            guard residual <= tolerance * scale else {
                continue
            }
            let solution = Tricubic3DInverseSolution(input: inputRGB, residual: residual)
            upsert(solution: solution, into: &roots)
        }
        // A finite Newton seed set cannot certify that all roots of the
        // tricubic cell were found. Preserve replay-validated roots for
        // diagnostics, but keep the cell unresolved until interval root
        // isolation is implemented.
        return CellResult(solutions: roots, unresolved: true)
    }

    private static func contains(_ target: RGB64,
                                 in bounds: [ClosedRange<Double>],
                                 tolerance: Double) -> Bool {
        let scale = max(1, abs(target.r), abs(target.g), abs(target.b))
        let margin = tolerance * scale
        return (0..<3).allSatisfy { axis in
            target[axis] >= bounds[axis].lowerBound - margin &&
                target[axis] <= bounds[axis].upperBound + margin
        }
    }

    private static func sameInput(_ a: RGB64, _ b: RGB64) -> Bool {
        let scale = max(1, abs(a.r), abs(a.g), abs(a.b), abs(b.r), abs(b.g), abs(b.b))
        let epsilon = 256 * Double.ulpOfOne * scale
        return abs(a.r - b.r) <= epsilon && abs(a.g - b.g) <= epsilon &&
            abs(a.b - b.b) <= epsilon
    }

    private static func upsert(solution: Tricubic3DInverseSolution,
                               into solutions: inout [Tricubic3DInverseSolution]) {
        if let index = solutions.firstIndex(where: { sameInput($0.input, solution.input) }) {
            if solution.residual < solutions[index].residual { solutions[index] = solution }
        } else {
            solutions.append(solution)
        }
    }

    private static func replayResidual(_ value: RGB64, target: RGB64) -> Double {
        max(abs(value.r - target.r), abs(value.g - target.g), abs(value.b - target.b))
    }
}
