// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "LUTKit",
    platforms: [.macOS(.v14), .iOS(.v17)],
    products: [
        .library(name: "LUTCore", targets: ["LUTCore"]),
        .library(name: "LUTCatalog", targets: ["LUTCatalog"]),
        .library(name: "LUTFormats", targets: ["LUTFormats"]),
        .library(name: "LUTAnalysis", targets: ["LUTAnalysis"]),
        .library(name: "LUTProject", targets: ["LUTProject"]),
        .library(name: "LUTJobs", targets: ["LUTJobs"]),
        .library(name: "LUTPreview", targets: ["LUTPreview"]),
        .library(name: "LUTSharedUI", targets: ["LUTSharedUI"]),
        .executable(name: "LUTContractChecks", targets: ["LUTContractChecks"]),
        .executable(name: "LUTReferenceCLI", targets: ["LUTReferenceCLI"]),
        .executable(name: "LUTJobChecks", targets: ["LUTJobChecks"]),
        .executable(name: "LUTBatchRecoveryChecks", targets: ["LUTBatchRecoveryChecks"]),
        .executable(name: "LUTSessionChecks", targets: ["LUTSessionChecks"]),
        .executable(name: "LUTAnalysisChecks", targets: ["LUTAnalysisChecks"]),
        .executable(name: "LUTCatalogChecks", targets: ["LUTCatalogChecks"]),
        .executable(name: "LUTProjectChecks", targets: ["LUTProjectChecks"]),
        .executable(name: "LUTProjectSessionChecks", targets: ["LUTProjectSessionChecks"]),
        .executable(name: "LUTPreviewChecks", targets: ["LUTPreviewChecks"]),
        .executable(name: "LUTImageChecks", targets: ["LUTImageChecks"]),
        .executable(name: "LUTFormatChecks", targets: ["LUTFormatChecks"]),
        .executable(name: "LUTRec709Checks", targets: ["LUTRec709Checks"]),
        .executable(name: "LUTSLog3Checks", targets: ["LUTSLog3Checks"]),
        .executable(name: "LUTLogC4Checks", targets: ["LUTLogC4Checks"]),
        .executable(name: "LUTVLogChecks", targets: ["LUTVLogChecks"]),
        .executable(name: "LUTAppleLogChecks", targets: ["LUTAppleLogChecks"]),
        .executable(name: "LUTHLGChecks", targets: ["LUTHLGChecks"]),
        .executable(name: "LUTBT1886Checks", targets: ["LUTBT1886Checks"]),
        .executable(name: "LUTBBCWHP283Checks", targets: ["LUTBBCWHP283Checks"]),
        .executable(name: "LUTDocumentChecks", targets: ["LUTDocumentChecks"]),
        .executable(name: "LUTDocumentExportChecks", targets: ["LUTDocumentExportChecks"]),
        .executable(name: "LUTDocumentSampleChecks", targets: ["LUTDocumentSampleChecks"]),
        .executable(name: "LUTCIELABChecks", targets: ["LUTCIELABChecks"]),
        .executable(name: "LUTPerformanceChecks", targets: ["LUTPerformanceChecks"]),
    ],
    targets: [
        .target(name: "LUTCore"),
        .target(name: "LUTCatalog", dependencies: ["LUTCore"]),
        .target(name: "LUTFormats", dependencies: ["LUTCore"]),
        .target(name: "LUTAnalysis", dependencies: ["LUTCore", "LUTFormats"]),
        .target(name: "LUTProject", dependencies: ["LUTCore", "LUTCatalog", "LUTFormats"]),
        .target(name: "LUTJobs", dependencies: ["LUTCore", "LUTFormats", "LUTAnalysis"]),
        .target(name: "LUTPreview", dependencies: ["LUTCore", "LUTFormats"]),
        .target(name: "LUTSharedUI", dependencies: ["LUTCatalog", "LUTFormats", "LUTAnalysis", "LUTJobs", "LUTProject", "LUTPreview"]),
        .executableTarget(name: "LUTContractChecks", dependencies: ["LUTCore", "LUTFormats"]),
        .executableTarget(name: "LUTReferenceCLI", dependencies: ["LUTCore", "LUTCatalog", "LUTFormats"]),
        .executableTarget(name: "LUTJobChecks", dependencies: ["LUTCore", "LUTFormats", "LUTJobs"]),
        .executableTarget(name: "LUTBatchRecoveryChecks", dependencies: ["LUTCore", "LUTJobs", "LUTSharedUI"]),
        .executableTarget(name: "LUTSessionChecks", dependencies: ["LUTSharedUI", "LUTCore", "LUTFormats", "LUTProject", "LUTCatalog"]),
        .executableTarget(name: "LUTAnalysisChecks", dependencies: ["LUTAnalysis"]),
        .executableTarget(name: "LUTCatalogChecks", dependencies: ["LUTCatalog", "LUTCore"]),
        .executableTarget(name: "LUTProjectChecks", dependencies: ["LUTProject", "LUTCatalog", "LUTCore"]),
        .executableTarget(name: "LUTProjectSessionChecks", dependencies: ["LUTProject", "LUTCatalog", "LUTCore"]),
        .executableTarget(name: "LUTPreviewChecks", dependencies: ["LUTPreview", "LUTCore", "LUTFormats"]),
        .executableTarget(name: "LUTImageChecks", dependencies: ["LUTPreview", "LUTCore", "LUTFormats"]),
        .executableTarget(name: "LUTFormatChecks", dependencies: ["LUTFormats", "LUTCore"]),
        .executableTarget(name: "LUTRec709Checks", dependencies: ["LUTCore", "LUTCatalog"]),
        .executableTarget(name: "LUTSLog3Checks", dependencies: ["LUTCore", "LUTCatalog"]),
        .executableTarget(name: "LUTLogC4Checks", dependencies: ["LUTCore", "LUTCatalog"]),
        .executableTarget(name: "LUTVLogChecks", dependencies: ["LUTCore", "LUTCatalog"]),
        .executableTarget(name: "LUTAppleLogChecks", dependencies: ["LUTCore", "LUTCatalog"]),
        .executableTarget(name: "LUTHLGChecks", dependencies: ["LUTCore"]),
        .executableTarget(name: "LUTBT1886Checks", dependencies: ["LUTCore"]),
        .executableTarget(name: "LUTBBCWHP283Checks", dependencies: ["LUTCore"]),
        .executableTarget(name: "LUTDocumentChecks", dependencies: ["LUTSharedUI", "LUTProject", "LUTCore", "LUTCatalog"]),
        .executableTarget(name: "LUTDocumentExportChecks", dependencies: ["LUTSharedUI", "LUTProject", "LUTCore", "LUTJobs", "LUTFormats"]),
        .executableTarget(name: "LUTDocumentSampleChecks", dependencies: ["LUTSharedUI", "LUTProject", "LUTCore", "LUTPreview"]),
        .executableTarget(name: "LUTCIELABChecks", dependencies: ["LUTCore"]),
        .executableTarget(name: "LUTPerformanceChecks", dependencies: ["LUTCore", "LUTFormats"]),
        .testTarget(name: "LUTCoreTests", dependencies: ["LUTCore", "LUTCatalog"]),
        .testTarget(name: "LUTFormatsTests", dependencies: ["LUTFormats"]),
        .testTarget(name: "LUTJobsTests", dependencies: ["LUTJobs", "LUTFormats", "LUTCore", "LUTAnalysis", "LUTSharedUI"]),
        .testTarget(name: "LUTSharedUITests", dependencies: ["LUTSharedUI", "LUTCore", "LUTFormats", "LUTJobs", "LUTProject", "LUTCatalog"]),
        .testTarget(name: "LUTAnalysisTests", dependencies: ["LUTAnalysis", "LUTFormats"]),
        .testTarget(name: "LUTCatalogTests", dependencies: ["LUTCatalog", "LUTCore"]),
        .testTarget(name: "LUTProjectTests", dependencies: ["LUTProject", "LUTCatalog", "LUTCore", "LUTFormats"]),
        .testTarget(name: "LUTPreviewTests", dependencies: ["LUTPreview", "LUTCore", "LUTFormats"]),
    ],
    swiftLanguageModes: [.v6]
)
