import Foundation
import XCTest
import LUTCore
import LUTFormats
@testable import LUTJobs

final class LocalCommitRaceContractsTests: XCTestCase {
    func testDefaultCommitNeverReplacesCompetitorCreatedAfterPrepare() async throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("lutcalc-commit-race-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: false)
        defer { try? FileManager.default.removeItem(at: directory) }

        for kind in [FileLUTFormat.cube, .spi3d] {
            let target = directory.appendingPathComponent("race-\(kind.rawValue).\(kind.rawValue)")
            let sink = FileCubeSink(target: target, format: kind)
            try await sink.prepare(size: 2, domain: .unit, title: "race")
            try await sink.append(blockIndex: 0, samples: Array(repeating: try RGB64(0.25, 0.5, 0.75), count: 8))
            try await sink.validate(expectedNodes: 8)
            let competing = Data("new owner".utf8)
            try competing.write(to: target)
            do {
                try await sink.commit()
                XCTFail("A late owner must not be overwritten")
            } catch FileSinkError.targetExists {}
            await sink.abort()
            XCTAssertEqual(try Data(contentsOf: target), competing)
            XCTAssertEqual(try FileManager.default.contentsOfDirectory(atPath: directory.path).sorted(),
                           [target.lastPathComponent])
            try FileManager.default.removeItem(at: target)
        }
    }

    func testCompetitorCreatedAtPublishBoundaryKeepsItsBytes() throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("lutcalc-publish-boundary-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: false)
        defer { try? FileManager.default.removeItem(at: directory) }
        let target = directory.appendingPathComponent("output.cube")
        let temporary = directory.appendingPathComponent(".lutcalc-contract.tmp")
        try Data("generated".utf8).write(to: temporary)
        let competing = Data("competing owner".utf8)
        XCTAssertThrowsError(try LocalFileCommit.publishNoOverwrite(temporary: temporary,
                                                                     target: target) {
            try competing.write(to: target)
        }) {
            XCTAssertEqual($0 as? FileSinkError, .targetExists)
        }
        XCTAssertEqual(try Data(contentsOf: target), competing)
        XCTAssertEqual(try Data(contentsOf: temporary), Data("generated".utf8))
    }

    func testCoordinatedPublishCommitsLocalFileWithoutChangingBytes() throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("lutcalc-coordinated-publish-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: false)
        defer { try? FileManager.default.removeItem(at: directory) }

        let target = directory.appendingPathComponent("output.cube")
        let temporary = directory.appendingPathComponent(".lutcalc-coordinated.tmp")
        let expected = Data("coordinated generated bytes\n".utf8)
        try expected.write(to: temporary, options: .atomic)

        try LocalFileCommit.publishNoOverwrite(temporary: temporary, target: target)

        XCTAssertEqual(try Data(contentsOf: target), expected)
        XCTAssertFalse(FileManager.default.fileExists(atPath: temporary.path))
    }

    func testCoordinatedPublishReportsProviderStyleCoordinationFailure() throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("lutcalc-coordinated-failure-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: false)
        defer { try? FileManager.default.removeItem(at: directory) }

        let target = directory.appendingPathComponent("missing-parent", isDirectory: true)
            .appendingPathComponent("output.cube")
        let temporary = directory.appendingPathComponent(".lutcalc-coordinated.tmp")
        try Data("generated".utf8).write(to: temporary, options: .atomic)

        XCTAssertThrowsError(try LocalFileCommit.publishNoOverwrite(temporary: temporary, target: target))
        XCTAssertTrue(FileManager.default.fileExists(atPath: temporary.path))
    }

    func testExplicitOverwriteRejectsReplacementWithSameBytesButDifferentFileIdentity() async throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("lutcalc-explicit-race-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: false)
        defer { try? FileManager.default.removeItem(at: directory) }

        let target = directory.appendingPathComponent("output.cube")
        let original = Data("same bytes".utf8)
        try original.write(to: target)
        let sink = FileCubeSink(target: target, allowOverwrite: true, format: .cube)
        try await sink.prepare(size: 2, domain: .unit, title: "race")
        try await sink.append(blockIndex: 0,
                              samples: Array(repeating: try RGB64(0.25, 0.5, 0.75), count: 8))
        try await sink.validate(expectedNodes: 8)

        try FileManager.default.removeItem(at: target)
        try original.write(to: target)

        do {
            try await sink.commit()
            XCTFail("An equal-byte replacement with a new file identity must be rejected")
        } catch FileSinkError.targetChanged {}
        await sink.abort()
        XCTAssertEqual(try Data(contentsOf: target), original)
    }

    func testCoordinatedExplicitOverwriteCommitsWhenOriginalIsUnchanged() throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("lutcalc-coordinated-overwrite-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: false)
        defer { try? FileManager.default.removeItem(at: directory) }

        let target = directory.appendingPathComponent("output.cube")
        let temporary = directory.appendingPathComponent(".lutcalc-overwrite.tmp")
        let oldBytes = Data("old owner".utf8)
        let newBytes = Data("new generated bytes".utf8)
        try oldBytes.write(to: target, options: .atomic)
        try newBytes.write(to: temporary, options: .atomic)
        let identity = try LocalFileCommit.fingerprint(target)

        try LocalFileCommit.replaceIfUnchanged(temporary: temporary, target: target,
                                               originalFingerprint: identity)

        XCTAssertEqual(try Data(contentsOf: target), newBytes)
        XCTAssertFalse(FileManager.default.fileExists(atPath: temporary.path))
    }

    func testMissingParentIsReportedBeforeAnyTemporaryFileIsCreated() throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("lutcalc-missing-parent-\(UUID().uuidString)", isDirectory: true)
        let target = directory.appendingPathComponent("output.cube")

        XCTAssertThrowsError(try LocalFileCommit.preflightDestination(target)) {
            XCTAssertEqual($0 as? FileSinkError, .destinationUnavailable)
        }
        XCTAssertFalse(FileManager.default.fileExists(atPath: directory.path))
    }

    func testSymlinkTargetIsRejectedBeforeCoordinatedPublish() async throws {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("lutcalc-symlink-target-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: false)
        defer { try? FileManager.default.removeItem(at: directory) }

        let realTarget = directory.appendingPathComponent("real.cube")
        let linkedTarget = directory.appendingPathComponent("linked.cube")
        try Data("existing".utf8).write(to: realTarget)
        try FileManager.default.createSymbolicLink(at: linkedTarget, withDestinationURL: realTarget)

        let sink = FileCubeSink(target: linkedTarget, allowOverwrite: true)
        do {
            try await sink.prepare(size: 2, domain: .unit, title: "symlink")
            XCTFail("A symlink target must be rejected before writing")
        } catch {
            XCTAssertEqual(error as? FileSinkError, .unsafeTarget)
        }
        XCTAssertEqual(try Data(contentsOf: realTarget), Data("existing".utf8))
    }
}
